WSAD-App1/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WSAD_App1.Models.Data;
using WSAD_App1.Models.ViewModels.Course;

namespace WSAD_App1.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Index()
        {
            //Setup a DBcontext
            List<EnrollSessionViewModel> collectionOfSessionVM = new List<EnrollSessionViewModel>();
            using (WSADDbContext context = new WSADDbContext())
            {
                //Get all sessions
                var dbSessions = context.Sessions;

                //Move users to ViewModel Object
                foreach (var sessionDTO in dbSessions)
                {
                    collectionOfSessionVM.Add(
                        new EnrollSessionViewModel(sessionDTO)
                        );
                }
            }
            //Send ViewModel Collete
            return View(collectionOfSessionVM);
        }


        [HttpPost]
        public ActionResult Enroll(List<EnrollSessionViewModel> collectionOfSessionsVM)
        {
            //Filter collectionOfUsers to find only Selected Items
            var vmItemsToEnroll = collectionOfSessionsVM.Where(x => x.IsSelected == true);

            //Get logged in user
            string username = User.Identity.Name;
            User userDTO;


            //Do Enroll

            using (WSADDbContext context = new WSADDbContext())
            {


                //Get user db info an Id
                userDTO = context.Users.FirstOrDefault(row => row.Username == username);
                int userId = userDTO.Id;
                //Loop through ViewModel Items to update
                foreach (var vmItem in vmItemsToEnroll)
                {
                    UserSession userSessionDTO = new UserSession();
                    var sessionDTO = context.Sessions.FirstOrDefault(row => row.Id == vmItem.Id);


                    userSessionDTO.User_Id = userId;
                    userSessionDTO.Session_Id = vmItem.Id;

                    //Check that session hasn't already been enrolled by user
                    if (context.UserSessions.Any(row => row.User_Id.Equals(userId)) && context.UserSessions.Any(row => row.Session_Id.Equals(vmItem.Id)))
                    {
                        TempData["error"] = "Error: You are already enrolled in this course.";
                        return RedirectToAction("Index");

                    }

                    else {
                        context.UserSessions.Add(userSessionDTO);
                    }

                }

                context.SaveChanges();
            }

            return RedirectToAction("Index", "Schedule");


        }

        [HttpGet]
        public ActionResult Details(int sessionId)
        {
            SessionViewModel sessionVM = new SessionViewModel();

            using (WSADDbContext context = new WSADDbContext())
            {
                Session session = context.Sessions.FirstOrDefault(row => row.Id == sessionId);
                sessionVM = new SessionViewModel(session);
            }

            return View(sessionVM);
        }
    }
}

WSAD-App1/Controllers/ManageUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WSAD_App1.Models.Data;
using WSAD_App1.Models.ViewModels.ManageUser;

namespace WSAD_App1.Controllers
{
    public class ManageUserController : Controller
    {
        // GET: ManageUser
        public ActionResult Index()
        {
            //Setup a DBcontext
            List<ManageUserViewModel> collectionOfUserVM = new List<ManageUserViewModel>();
            using (WSADDbContext context = new WSADDbContext())
            {
                //Get all users
                var dbUsers = context.Users;

                //Move users to ViewModel Object
                foreach (var userDTO in dbUsers)
                {
                    collectionOfUserVM.Add(
                        new ManageUserViewModel(userDTO)
                        );
                }
            }
            //Send ViewModel Collete
            return View(collectionOfUserVM);
        }

        [HttpPost]
        public ActionResult Delete(List<ManageUserViewModel> collectionOfUsersVM)
        {
            //Filter collectionOfUsers to find only Selected Items
            var vmItemsToDelete = collectionOfUsersVM.Where(x => x.IsSelected == true);

            //Do delete

            using (WSADDbContext context = new WSADDbContext())
            {
                //Loop through ViewModel Items to delete
                foreach (var vmItem in vmItemsToDelete)
                {
                    var dtoToDelete = context.Users.FirstOrDefault(row => row.Id == vmItem.Id);
                    context.Users.Remove(dtoToDelete);
                }

                context.SaveChanges();
            }
                return RedirectToAction("Index");
            
        }
    }
}

WSAD-App1/Controllers/correspondenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WSAD_App1.Models.Data;
using WSAD_App1.Models.ViewModels.Correspondence;

namespace WSAD_App1.Controllers
{
    public class CorrespondenceController : Controller
    {
        // GET: correspondence
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactEmailViewModel contactMessage)
        {
            //Validate Contact Message Input
            if (contactMessage == null)
            {
                ModelState.AddModelError("","No Message Provided");
                return View();
            }

            if (string.IsNullOrWhiteSpace(contactMessage.Name) ||
                string.IsNullOrWhiteSpace(contactMessage.Email) ||
                string.IsNullOrWhiteSpace(contactMessage.Message))
            {
                ModelState.AddModelError("", "All fields are required.");
            }

            //Create an Email Message Object
            MailMessage email = new MailMessage();
            email.To.Add("millssk@mail.uc.edu");
            email.From = new MailAddress(contactMessage.Email);
            email.Subject = "This is our correspondence";
            email.Body = string.Format(
                "Name: {0}\r\nMessage: {1}",
                    contactMessage.Name,
                    contactMessage.Message
            );

            //Setup SMTP Client
            SmtpClient smtpClient = new SmtpClient();
            smtpClient.Host = "smtp.gmail.com";
            System.Net.NetworkCredential basicauthenticationinfo = new System.Net.NetworkCredential("millsskUCAppTest@gmail.com", "$koolRoolz");
            smtpClient.Port = int.Parse("587");
            smtpClient.EnableSsl = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Credentials = basicauthenticationinfo;
            smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
            
            //Send EMail
            smtpClient.Send(email);

            //Save to DB
            saveCorrespondence(contactMessage);

            //Notify user message was sent
            return View("emailConfirmation");
        }

        public void saveCorrespondence(ContactEmailViewModel contactMessage)
        {
            //Create DBContext instance
            using (WSADDbContext context = new WSADDbContext())
            {
                //Create correspondenceDTO
                Correspondence correspondenceDTO = new Correspondence()
                {
                    Name = contactMessage.Name,
                    Email = contactMessage.Email,
                    Message = contactMessage.Message
                };

                //Add to DbContext
                correspondenceDTO = context.Correspondences.Add(correspondenceDTO);

                //Save changes
                context.SaveChanges();
            }

        }
    }
}

WSAD-App1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IT Training", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Enroll", "Index", "Course", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Schedule", "Index", "Schedule", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "Correspondence", new { area = "" }, null)</li>
                    @if(Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Logout","Logout","Account")</li>
                        <li>@Html.Action("UserNavPartial","Account", new { area = "" })</li>
                        <li>@Html.ActionLink("Manage Users", "Index", "ManageUser", new { area = "Admin" }, null)</li>
                        <li>@Html.ActionLink("Manage Sessions", "Index", "ManageSession", new { area = "Admin" }, null)</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Login","Login","Account")</li>
                    }
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>