WSAD-App1/Areas/Admin/Models/ViewModels/ManageSession/CreateSessionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WSAD_App1.Areas.Admin.Models.ViewModels.ManageSession
{
    public class CreateSessionViewModel
    {
        [Required]
        public string Course { get; set; }
        [Required]
        public string Instructor { get; set; }
        [Required]
        public string MeetingDate { get; set; }
        [Required]
        public string MeetingTime { get; set; }
        [Required]
        public string Description { get; set; }
        //public int Occupancy { get; set; }
    }
}

WSAD-App1/Areas/Admin/Models/ViewModels/ManageSession/ManageSessionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WSAD_App1.Models.Data;

namespace WSAD_App1.Areas.Admin.Models.ViewModels.ManageSession
{
    public class ManageSessionViewModel
    {
        public ManageSessionViewModel()
        {

        }

        public ManageSessionViewModel(Session sessionDTO)
        {
            this.Id = sessionDTO.Id;
            this.Course = sessionDTO.Course;
            this.Instructor = sessionDTO.Instructor;
            this.MeetingDate = sessionDTO.MeetingDate;
            this.MeetingTime = sessionDTO.MeetingTime;
            this.Occupancy = sessionDTO.Occupancy;
            this.Description = sessionDTO.Description;
        }
        public int Id { get; set; }
        public string Course { get; set; }
        public string Instructor { get; set; }
        public string MeetingDate { get; set; }
        public string MeetingTime { get; set; }
        public int Occupancy { get; set; }
        public string Description { get; set; }
        public bool IsSelected { get; set; }
    }
}

WSAD-App1/Areas/Admin/Controllers/ManageSessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WSAD_App1.Models.Data;
using WSAD_App1.Areas.Admin.Models.ViewModels.ManageSession;


namespace WSAD_App1.Areas.Admin.Controllers
{
    [Authorize(Roles="Admin")]
    public class ManageSessionController : Controller
    {
        // GET: ManageSession
        public ActionResult Index()
        {
            //Setup a DBcontext
            List<ManageSessionViewModel> collectionOfSessionVM = new List<ManageSessionViewModel>();
            using (WSADDbContext context = new WSADDbContext())
            {
                //Get all Sessions
                var dbSessions = context.Sessions;

                //Move Sessions to ViewModel Object
                foreach (var SessionDTO in dbSessions)
                {
                    collectionOfSessionVM.Add(
                        new ManageSessionViewModel(SessionDTO)
                        );
                }
            }
            //Send ViewModel Collete
            return View(collectionOfSessionVM);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateSessionViewModel newSession)
        {
            //Check required fields
            if (!ModelState.IsValid)
            {
                return View(newSession);
            }

            //Create DbContext
            using (WSADDbContext context = new WSADDbContext())
            {
                //Check for duplicate sessions
                if (context.Sessions.Any(row => row.Course.Equals(newSession.Course)))
                {
                    ModelState.AddModelError("", "Session '" + newSession.Course + "' already exists. Try Again");
                    newSession.Course = "";
                    return View(newSession);
                }

                //Create Session DTO
                Session newSessionDTO = new WSAD_App1.Models.Data.Session()
                {
                    Course = newSession.Course,
                    Instructor = newSession.Instructor,
                    MeetingDate = newSession.MeetingDate,
                    MeetingTime = newSession.MeetingTime,
                    Description = newSession.Description

                };

                //Add to DbContext

                newSessionDTO = context.Sessions.Add(newSessionDTO);

                //Save changes
                context.SaveChanges();
            }

            //Redirect to login
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(List<ManageSessionViewModel> collectionOfSessionsVM)
        {
            //Filter collectionOfSessions to find only Selected Items
            var vmItemsToDelete = collectionOfSessionsVM.Where(x => x.IsSelected == true);

            //Do delete

            using (WSADDbContext context = new WSADDbContext())
            {
                //Loop through ViewModel Items to delete
                foreach (var vmItem in vmItemsToDelete)
                {
                    var dtoToDelete = context.Sessions.FirstOrDefault(row => row.Id == vmItem.Id);
                    context.Sessions.Remove(dtoToDelete);
                }

                context.SaveChanges();
            }
                return RedirectToAction("Index");
            
        }
    }
}

WSAD-App1/Areas/Admin/Views/ManageSession/Create.cshtml
@model WSAD_App1.Areas.Admin.Models.ViewModels.ManageSession.CreateSessionViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateSessionViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MeetingTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MeetingTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MeetingTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WSAD-App1/Areas/Admin/Views/ManageSession/Index.cshtml
@model List<WSAD_App1.Areas.Admin.Models.ViewModels.ManageSession.ManageSessionViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Manage Sessions</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Delete", "ManageSession"))
{
    <button type="submit" class="btn btn-danger">Delete Session(s)</button>

<table class="table">
    <tr>
        <th>&nbsp;</th>
        <th>
            Course
        </th>
        <th>
            Instructor
        </th>
        <th>
            Meeting Date
        </th>
        <th>
            MeetingTime
        </th>
        <th>
            Occupancy
        </th>
        <th>
          Manage
        </th>
        <th></th>
    </tr>

@*foreach (var item in Model)*@
@for (int i = 0; i < Model.Count; i++)
{
    var item = Model[i];
    <tr>
        <td>
            @Html.HiddenFor(x => Model[i].Id)
            @Html.CheckBoxFor(x => Model[i].IsSelected)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Instructor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MeetingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MeetingTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Occupancy)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
    <button type="submit" class="btn btn-danger">Delete Session(s)</button>
}