WSAD-App1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WSAD_App1.Controllers
{

    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WSAD-App1/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WSAD_App1.Models.Data;
using WSAD_App1.Models.ViewModels.Schedule;

namespace WSAD_App1.Controllers
{
    [Authorize]
    public class ScheduleController : Controller
    {
        // GET: CourseCart
        public ActionResult Index()
        {
            List<EnrolledSessionViewModel> enrolledSessions = new List<EnrolledSessionViewModel>();

            using (WSADDbContext context = new WSADDbContext())
            {
                //Get User info
                string username = User.Identity.Name;

                //Get user id from DB
                var userId = context.Users
                    .Where(x => x.Username == username)
                    .Select(x => x.Id)
                    .FirstOrDefault();

                //Get Enrolled sessions
                enrolledSessions = context.UserSessions.Where(x => x.User_Id == userId)
                    .ToArray()
                    .Select(x => new EnrolledSessionViewModel(x))
                    .ToList();


                //Generated Schedule view model
            }
                return View(enrolledSessions);
        }

        [HttpPost]
        public ActionResult Delete(List<EnrolledSessionViewModel> collectionOfSessionsVM)
        {
            //Get sessions to delete

            var vmItemsToDelete = collectionOfSessionsVM.Where(x => x.IsSelected == true);

            //Do delete

            using (WSADDbContext context = new WSADDbContext())
            {
                //Loop through ViewModel Items to delete
                foreach (var vmItem in vmItemsToDelete)
                {
                    var dtoToDelete = context.UserSessions.FirstOrDefault(row => row.Session_Id == vmItem.Session_Id);
                    context.UserSessions.Remove(dtoToDelete);
                }

                context.SaveChanges();
            }

            TempData["success"] = "Successfully unenrolled from course(s)";
            return RedirectToAction("Index");
        }
    }
}

WSAD-App1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WSAD-App1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WSAD-App1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Top IT Training</h1>
    <p class="lead">Welcome to the best online training program currently on your computer display.</p>
    <p>@Html.ActionLink("Login", "Login", "Account", new { area = "", @class = "btn btn-primary btn-lg"}, null)</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Sign Up!</h2>
        <p>
            Sign up for classes today and advance your knowledge and career!
        </p>
        <p>@Html.ActionLink("View Courses", "Index", "Schedule", new { area = "" }, null)</p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">        
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>